// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WeatherComparator.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Get_Weather_Data_From_NDTV_Web", new string[] {
            "regression"}, Description="\tIn order to avoid failures\r\n\tAs an automation tester\r\n\tI want to verify the \"Pin" +
        " your city\" functionality in NDTV\'s weather section and build weather Object 1 f" +
        "or comparison", SourceFile="features\\Get_Weather_Data_From_NDTV_Web.feature", SourceLine=1)]
    public partial class Get_Weather_Data_From_NDTV_WebFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Get_Weather_Data_From_NDTV_Web.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Get_Weather_Data_From_NDTV_Web", "\tIn order to avoid failures\r\n\tAs an automation tester\r\n\tI want to verify the \"Pin" +
                    " your city\" functionality in NDTV\'s weather section and build weather Object 1 f" +
                    "or comparison", ProgrammingLanguage.CSharp, new string[] {
                        "regression"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ValidateIfCorrespondingCityIsAvailableOnTheMapValidateTheWeatherDetailsOnClickingTheCity(string description, string city, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web",
                    "phase_1",
                    "tc_001"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate if corresponding city is available on the map & validate the weather det" +
                    "ails on clicking the city", null, @__tags);
#line 9
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 10
testRunner.Given(string.Format("Load scenario outline description \'{0}\'", description), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
testRunner.Given("I open the website\'s home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
testRunner.When("I navigate to the weather section of the website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
testRunner.And(string.Format("I select a city: \'{0}\' using Pin Your City from the left", city), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
testRunner.Then(string.Format("I should see that corresponding city \'{0}\' is available on the map with temperatu" +
                        "re information", city), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
testRunner.When(string.Format("I select the city \'{0}\' on the map", city), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
testRunner.Then(string.Format("I should see the corresponding city\'s \'{0}\' weather details", city), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate if corresponding city is available on the map & validate the weather det" +
            "ails on clicking the city, NDTVWeatherCoimbatore", new string[] {
                "web",
                "phase_1",
                "tc_001"}, SourceLine=18)]
        public virtual void ValidateIfCorrespondingCityIsAvailableOnTheMapValidateTheWeatherDetailsOnClickingTheCity_NDTVWeatherCoimbatore()
        {
#line 9
this.ValidateIfCorrespondingCityIsAvailableOnTheMapValidateTheWeatherDetailsOnClickingTheCity("NDTVWeatherCoimbatore", "Coimbatore", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate if corresponding city is available on the map & validate the weather det" +
            "ails on clicking the city, NDTVWeatherAhmedabad", new string[] {
                "web",
                "phase_1",
                "tc_001"}, SourceLine=18)]
        public virtual void ValidateIfCorrespondingCityIsAvailableOnTheMapValidateTheWeatherDetailsOnClickingTheCity_NDTVWeatherAhmedabad()
        {
#line 9
this.ValidateIfCorrespondingCityIsAvailableOnTheMapValidateTheWeatherDetailsOnClickingTheCity("NDTVWeatherAhmedabad", "Ahmedabad", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
